###
GET http://localhost:3005/booking-pinjam

###
POST http://localhost:3005/booking-pinjam
Content-Type: application/json

{
  "Siswa_NIS": 105219099,
  "Buku_kodeBuku": "1.2.10",
  "tglPemesanan": "2023-08-05"
}

###
PUT http://localhost:3005/booking-pinjam/1
Content-Type: application/json

    {
        "Buku_kodeBuku": "1.2.10",
        "Siswa_NIS": 15151,
        "idReservasi": 1,
        "tglPemesanan": "2023-08-05",
        "status": "Kadaluarsa",
        "createdAt": "2023-08-29T20:12:23.000Z",
        "judul": "Bisnis Franchise",
        "nama": "Rizky"
    }


###
DELETE http://localhost:3005/booking-pinjam/3