GET http://localhost:3005/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjozLCJuYW1lIjoiQWhtYWQiLCJ1c2VybmFtZSI6ImFkbWluMyIsImlhdCI6MTY5MDE4OTczNiwiZXhwIjoxNjkwMTg5NzU2fQ.npBuKUezoJHnL-4MHwyOG5m1u_Vz2Qu95F51cj_HbjY


###
POST http://localhost:3005/admin
Content-Type: application/json

{
  "name" : "Windu",
  "username": "admin4",
  "password": "perpustakaan1945", 
  "confPassword": "perpustakaan1945"
}

###
POST http://localhost:3005/login
Content-Type: application/json

{
  "username" : "admin3",
  "password" : "perpustakaan1945"
}

###
GET http://localhost:3005/token

###
DELETE http://localhost:3005/logout


###
GET http://localhost:3005/siswatoken/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaXN3YUlkIjoiMTA1MjE5MDEwIiwiTmFtYSI6Ik1hbWFkIiwiaWF0IjoxNjg4NjM4ODQ3LCJleHAiOjE2ODg2MzkxNDd9.06AUiYNDkxMzz2jFPbX0AWfQa1mr43-ED-Jw_EWJ7OQ

###
POST http://localhost:3005/admin
Content-Type: application/json

{
  "name" : "Windu",
  "username": "admin4",
  "password": "perpustakaan1945", 
  "confPassword": "perpustakaan1945"
}

###
POST http://localhost:3005/siswa/login
Content-Type: application/json

{
  "Nama" : "AldoGian",
  "password" : "12345678"
}

###
GET http://localhost:3005/token

###
DELETE http://localhost:3005/logout

###
GET http://localhost:3005/siswa

###
POST http://localhost:3005/siswa
Content-Type: application/json

{
  "NIS" : "15151",
  "Nama": "Rizky",
  "Kelas": "12",
  "Jurusan" : "IPA-1"
}

###
GET http://localhost:3005/peminjaman

###
POST http://localhost:3005/peminjaman

{
    "kodeBuku": "1.2.6",
    "NIS": 1231234,
    "namaPeminjam": "Tes",
    "judulBuku": "Introduce to Software Engineering",
    "tglKembali": null,
    "batasPinjam": "7-25-2023",
    "tglPinjam": "7-22-2023",
    "status": "Belum Dikembalikan",
    "denda": "",
}

###
GET http://localhost:3005/book/search/kimia

###
GET http://localhost:3005/book/pdf/10

###
GET https://api2.librarysmayuppentek.sch.id/book/

###
DELETE http://localhost:3005/peminjaman/35

###
DELETE http://localhost:3005/siswaLogout

###
PUT https://api2.librarysmayuppentek.sch.id/book/10

{
  "judul": "Ekonomi",
  "penulis" : "Ending Mulyani, Asep Nurcahyanto",
  "kategori" : "Ekonomi",
  "ringkasan": "AAAAAA",
  "tahun_terbit": "2006",
  "keterangan": "Buku Fisik",
  "jumlah": "2",
  "cover_buku" : null,
  "file_ebook" : null
}